name: Build Armbian Images
on:
  release:
    types: [created]  # published?
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old Dev assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: 'Dev'
          REPO: ${{ github.repository }}
        run: |
          echo "Checking for old ${{ env.TAG }} assets to delete"
          if gh release view ${{ env.TAG }} --repo ${{ env.REPO }} > /dev/null 2>&1; then
            # if the tag exists, find all assets
            for asset in $(gh release view ${{ env.TAG }} --json assets --repo ${{ env.REPO }} --jq '.assets[].name'); do
              if [[ ${{ github.ref}} == 'refs/heads/main' ]]; then
                # only delete assets for Dev release when running on main branch
                echo "Deleting asset: $asset"
                gh release delete-asset ${{ env.TAG }} "$asset" --repo ${{ env.REPO }} --yes
              else
                echo "Not on main branch, skipping deletion of asset: $asset"
              fi
            done
          else
            echo "Release ${{ env.TAG }} does not exist, no assets to delete"
          fi

  build:
    runs-on: ubuntu-latest
    needs: clean
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        board:
          - "orangepi5"
          - "orangepi5b"
          - "orangepi5pro"
          - "orangepi5-max"
          - "orangepi5-plus"
          - "rock-5c"
    env:
      ARMBIAN_ARTIFACTS: ${{ github.workspace }}/build/output/images/
    steps:
      - name: Build Armbian Images and Release
        uses: armbian/build@main
        id: build
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: ${{ matrix.board }}
          armbian_release: "trixie"
          # armbian_version: "26.5.1" # this doesn't work. The build script will always use the latest version
          armbian_target: "build"
          armbian_kernel_branch: "vendor"
          armbian_ui: "minimal"
          # armbian_runner_clean: "yes" # the runners have a lot of disk space, so no need to clean up
          armbian_release_tag:  ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || 'Dev' }}
          armbian_release_title: ${{ github.event.release.name || 'Dev release' }}
          armbian_artifacts: ${{ env.ARMBIAN_ARTIFACTS }}
          armbian_release_prerelease: ${{ startsWith(github.ref, 'refs/tags/v') && 'false' || 'true' }}
          armbian_release_body: ${{ github.event.release.body || 'Dev release' }}
        continue-on-error: true
      - uses: actions/upload-artifact@v7
        name: Upload artifacts
        if: steps.build.outcome == 'failure'
        with:
          archive: false
          path: ${{ env.ARMBIAN_ARTIFACTS }}/*.img.xz
          if-no-files-found: error
          retention-days: 7
  
  all-builds-passed:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - name: Check if all builds passed
        run: |
          if [[ ${{ needs.build.result }} == 'success' ]]; then
            echo "All builds passed."
          else
            echo "Some builds failed."
            exit 1
          fi
